version: '3.8'
services:
  composer:
    image: composer
    container_name: composer.php
    ports:
      - "9001:9000"
    volumes:
      - .:/composer
    working_dir: /composer
    command: bash -c "chmod -R 777 . && composer install && composer dump-autoload"

  php:
    build: ./docker/php
    image: 'php-apache-server'
    container_name: "php7.4-apache-server"
    volumes:
      - .:/var/www/hcode
    ports:
      - "8088:80"
    restart: always

  mysql-db:
    image: mysql:8.0
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - "3359:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: "phpmyadmin-srv"
   ports:
     - 8084:80
   environment:
     PMA_HOST: mysql-db
   restart: always
   depends_on:
     - mysql-db