version: '3.8'
services:
  composer:
    image: composer
    container_name: composer.php
    ports:
      - 9001:9000
    volumes:
      - .:/composer
    working_dir: /composer
    command: bash -c "chmod -R 777 . && composer install && composer dump-autoload"

  php:
    build: ./docker/build/php
    image: 'php-apache-server'
    container_name: "php7.4-apache-server"
    volumes:
      - .:/var/www/graphql
    working_dir: /var/www/graphql
    ports:
      - 8088:80
    restart: always

  mysql-db:
    image: mysql:8.0
    container_name: "mysql-db-container"
    volumes:
      #Local dos arquivos/dados do banco de dados
      - ./docker/data/db:/var/lib/mysql 
      #Pasta com script onde executa o script de criação do banco
      - ./docker/build/scripts/db:/docker-entrypoint-initdb.d
    ports:
      - "3359:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    restart: always

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: "phpmyadmin-srv"
   ports:
     - 8084:80
   environment:
     PMA_HOST: mysql-db
   restart: always
   depends_on:
     - mysql-db